//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class shenpi
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string software { get; set; }
        public string model { get; set; }
        public string version { get; set; }
        public string model_tips { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public Nullable<int> is_read { get; set; }
        public Nullable<int> is_through { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public Nullable<System.DateTime> read_time { get; set; }
    }
}
